version: '2'

<<<<<<< HEAD
  device-auth-server:
    build: ./device-auth-server  # Location of the Node.js server code
    environment:
      - OIDC_ISSUER_URL=https://keycloak-server/auth/realms/myrealm
      - OIDC_CLIENT_ID=myclient
      - OIDC_CLIENT_SECRET=mysecret
    ports:
      - "3000:3000"

      ### all env variables still need correct values
=======
volumes:
  settings:                          # Only required if using PERSISTENT flag (see below)

services:

  browser:
    build: .
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
>>>>>>> parent of e8a16bd (Added new docker-composer.yml and server.js file)
