version: '2'
services:
  browser:
    image: bh.cr/balenalabs/browser-$BALENA_ARCH/2.7.0
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    restart: always
    environment:
      - KIOSK=1
      - KIOSK_URL=http://dashing.local
      - SHOW_CURSOR=0

device-auth-server:
    build: ./device-auth-server  # Location of the Node.js server code
    environment:
      - OIDC_ISSUER_URL=https://keycloak-server/auth/realms/myrealm
      - OIDC_CLIENT_ID=myclient
      - OIDC_CLIENT_SECRET=mysecret
    ports:
      - "3000:3000"

      ### all env variables still need correct values
